name: Publish to the NPM registry

on:
  workflow_dispath:
#   push:
#     branches:
#      - main
#    paths:
#      # There might be a new version to be published
#      - package.json
#      # The lock file changed
#      - pnpm-lock.json
#      # Tests changed and may pass now
#      - __tests__/**/*
#      # Samples used for testing changed
#      - samples/**/*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Set config for publishing
        run: pnpm config set "//registry.npmjs.org/:_authToken" $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish
        run: pnpm publish --access public
