name: Verify code quality

on:
  pull_request:
    branches:
      - main
    paths:
      # There might be a new version to be published
      - package.json
      # Tests changed and may pass now
      - __tests__/**/*
      # Samples changed and tests may pass now
      - samples/**/*
      # Source code changed and tests may pass now
      - src/**/*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test